# Generated by Django 5.2.17 on 2026-08-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('theme', models.JSONField(blank=True, default=dict, help_text='Brand tokens e.g. {primary, accent}')),
                ('domains', models.JSONField(blank=True, default=list, help_text='Allowed storefront hostnames for this company')),
                ('is_active', models.BooleanField(default=True)),
                ('storefront_enabled', models.BooleanField(default=False, help_text='False for AM until its website launches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('ga_measurement_id', models.CharField(blank=True, help_text='GA4 Measurement ID — different per company', max_length=64)),
                ('paysafe_account_id', models.CharField(blank=True, max_length=128)),
                ('paysafe_public_key_hint', models.CharField(blank=True, help_text='Optional short label for which merchant account is wired', max_length=64)),
                ('shipping_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'company settings',
            },
        ),
    ]
